name: IWYU CI

on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - ubuntu-20.04
          - macos-10.15
    steps:
      - name: Setup Mingw
        if: contains(matrix.os, 'windows')
        uses: aminya/setup-cpp@v1
        with:
          gcc: true

      - name: Setup Clang, CMake, Ninja
        uses: aminya/setup-cpp@v1
        with:
          compiler: llvm-13.0.0
          cmake: true
          ninja: true

      - name: Check out default branch
        uses: actions/checkout@v2

      - name: Build include-what-you-use Windows
        if: contains(matrix.os, 'windows')
        run: |
          cmake -S ./ -B ./build -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=~/llvm
          cmake --build ./build --config Release

      - name: Build include-what-you-use
        run: |
          cmake -S ./ -B ./build -G Ninja -DCMAKE_INSTALL_PREFIX=~/llvm -DCMAKE_FIND_FRAMEWORK=LAST
          cmake --build ./build --config Release

      - name: Test include-what-you-use
        run: |
          cd ./build
          CTEST_OUTPUT_ON_FAILURE=1 ctest -j 6

      - name: Test install
        run: |
          cd ./build
          cmake --install .

      - name: Check license headers
        run: |
          git ls-tree --full-tree --name-only -r HEAD | \
              xargs ./iwyu-check-license-header.py

      - name: Upload Binaries
        uses: actions/upload-artifact@v2
        with:
          path: |
            ./build
          retention-days: 1
